---
title: "Get human ortholog for pig gene names"
author: "Kimberly Olney"
date: "7/26/2022"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---


```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = ".")
```

```{r, message = FALSE, warning = FALSE, echo = FALSE, include = FALSE}
library(geneName)
library(plotly)
library(tidyverse)
library(htmlwidgets)
library(ggvenn)
library(dplyr)
library(gprofiler2)
library(stats)
```

# Read in DEG tables
```{r}
tool <- "star"
pig_brain_FDRq1.00 <-
  read.delim("../../results/star/DEGs/LPS_Brain_gene_DEGs_FDRq1.00.txt")

pig_kidney_FDRq1.00 <-
  read.delim("../../results/star/DEGs/LPS_Kidney_gene_DEGs_FDRq1.00.txt")

pig_blood_FDRq1.00 <-
  read.delim("../../results/star/DEGs/LPS_Blood_gene_DEGs_FDRq1.00.txt")
```

# Orthologs
Convert mouse and pig gene_ids to human gene symbols 
https://cran.r-project.org/web/packages/gprofiler2/vignettes/gprofiler2.html
```{r}
human_pig_brain_orth <-
  gorth(
    query = pig_brain_FDRq1.00$gene_id,
    source_organism = "sscrofa",
    target_organism = "hsapiens",
    mthreshold = Inf,
    filter_na = TRUE,
    numeric_ns = "ENTREZGENE_ACC"
  )

human_pig_kidney_orth <-
  gorth(
    query = pig_brain_FDRq1.00$gene_id,
    source_organism = "sscrofa",
    target_organism = "hsapiens",
    mthreshold = Inf,
    filter_na = TRUE,
    numeric_ns = "ENTREZGENE_ACC"
  )

human_pig_blood_orth <-
  gorth(
    query = pig_brain_FDRq1.00$gene_id,
    source_organism = "sscrofa",
    target_organism = "hsapiens",
    mthreshold = Inf,
    filter_na = TRUE,
    numeric_ns = "ENTREZGENE_ACC"
  )
```
# Merge ortholog name with the species gene id
### Brain
```{r}
tissue <- "Brain"
treatment <- "LPS"

human_pig_brain_orth$gene_id <- human_pig_brain_orth$input
pig_brain_FDRq1.00_orth <-
  merge(pig_brain_FDRq1.00,
        human_pig_brain_orth,
        by = "gene_id",
        all.x = TRUE)

pig_brain_FDRq1.00_orth <-
  pig_brain_FDRq1.00_orth %>% mutate(ortholog_name = coalesce(ortholog_name, gene_name))
pig_brain_FDRq0.05_up_regulated <- subset(pig_brain_FDRq1.00_orth, logFC > 0 & adj.P.Val < 0.05)
pig_brain_FDRq0.05_down_regulated <- subset(pig_brain_FDRq1.00_orth, logFC < 0 & adj.P.Val < 0.05)

write.table(
  pig_brain_FDRq1.00_orth,
  paste0(
    "../../results/",
    tool,
    "/gprofiler/",
    treatment,
    "_",
    tissue,
    "_gene_DEGs_FDRq1.00_orth.txt"
  ),
  sep = "\t",
  row.names = FALSE,
  quote = FALSE
)

write.table(
  pig_brain_FDRq0.05_up_regulated,
  paste0(
    "../../results/",
    tool,
    "/gprofiler/",
    treatment,
    "_",
    tissue,
    "_gene_DEGs_FDRq0.05_up_regulated_orth.txt"
  ),
  sep = "\t",
  row.names = FALSE,
  quote = FALSE
)


write.table(
  pig_brain_FDRq0.05_down_regulated,
  paste0(
    "../../results/",
    tool,
    "/gprofiler/",
    treatment,
    "_",
    tissue,
    "_gene_DEGs_FDRq0.05_down_regulated_orth.txt"
  ),
  sep = "\t",
  row.names = FALSE,
  quote = FALSE
)
```
### Kidney
```{r}
tissue <- "Kidney"
treatment <- "LPS"

human_pig_kidney_orth$gene_id <- human_pig_kidney_orth$input
pig_kidney_FDRq1.00_orth <-
  merge(pig_kidney_FDRq1.00,
        human_pig_kidney_orth,
        by = "gene_id",
        all.x = TRUE)

pig_kidney_FDRq1.00_orth <-
  pig_kidney_FDRq1.00_orth %>% mutate(ortholog_name = coalesce(ortholog_name, gene_name))
pig_kidney_FDRq0.05_up_regulated <- subset(pig_kidney_FDRq1.00_orth, logFC > 0 & adj.P.Val < 0.05)
pig_kidney_FDRq0.05_down_regulated <- subset(pig_kidney_FDRq1.00_orth, logFC < 0 & adj.P.Val < 0.05)

write.table(
  pig_kidney_FDRq1.00_orth,
  paste0(
    "../../results/",
    tool,
    "/gprofiler/",
    treatment,
    "_",
    tissue,
    "_gene_DEGs_FDRq1.00_orth.txt"
  ),
  sep = "\t",
  row.names = FALSE,
  quote = FALSE
)

write.table(
  pig_kidney_FDRq0.05_up_regulated,
  paste0(
    "../../results/",
    tool,
    "/gprofiler/",
    treatment,
    "_",
    tissue,
    "_gene_DEGs_FDRq0.05_up_regulated_orth.txt"
  ),
  sep = "\t",
  row.names = FALSE,
  quote = FALSE
)


write.table(
  pig_kidney_FDRq0.05_down_regulated,
  paste0(
    "../../results/",
    tool,
    "/gprofiler/",
    treatment,
    "_",
    tissue,
    "_gene_DEGs_FDRq0.05_down_regulated_orth.txt"
  ),
  sep = "\t",
  row.names = FALSE,
  quote = FALSE
)
```
### Blood
```{r}
tissue <- "blood"
treatment <- "LPS"

human_pig_blood_orth$gene_id <- human_pig_blood_orth$input
pig_blood_FDRq1.00_orth <-
  merge(pig_blood_FDRq1.00,
        human_pig_blood_orth,
        by = "gene_id",
        all.x = TRUE)

pig_blood_FDRq1.00_orth <-
  pig_blood_FDRq1.00_orth %>% mutate(ortholog_name = coalesce(ortholog_name, gene_name))
pig_blood_FDRq0.05_up_regulated <- subset(pig_blood_FDRq1.00_orth, logFC > 0 & adj.P.Val < 0.05)
pig_blood_FDRq0.05_down_regulated <- subset(pig_blood_FDRq1.00_orth, logFC < 0 & adj.P.Val < 0.05)

write.table(
  pig_blood_FDRq1.00_orth,
  paste0(
    "../../results/",
    tool,
    "/gprofiler/",
    treatment,
    "_",
    tissue,
    "_gene_DEGs_FDRq1.00_orth.txt"
  ),
  sep = "\t",
  row.names = FALSE,
  quote = FALSE
)

write.table(
  pig_blood_FDRq0.05_up_regulated,
  paste0(
    "../../results/",
    tool,
    "/gprofiler/",
    treatment,
    "_",
    tissue,
    "_gene_DEGs_FDRq0.05_up_regulated_orth.txt"
  ),
  sep = "\t",
  row.names = FALSE,
  quote = FALSE
)


write.table(
  pig_blood_FDRq0.05_down_regulated,
  paste0(
    "../../results/",
    tool,
    "/gprofiler/",
    treatment,
    "_",
    tissue,
    "_gene_DEGs_FDRq0.05_down_regulated_orth.txt"
  ),
  sep = "\t",
  row.names = FALSE,
  quote = FALSE
)
```