---
title: "Upset Plot isoform level among tissues"
author: "Kimberly Olney"
date: "08/02/2022"
output: html_document
---

# Setup

```{r setup, include=FALSE}
# Also do Session > Set Working Directory > Choose Directory
knitr::opts_knit$set(root.dir = ".")
```

```{r packages}
library(UpSetR)
library(ComplexUpset)
library(ggplot2movies)
```

# Read in DEGs

```{r}
kallisto_brain <- read.delim("../../results/kallisto/DEGs/LPS_Brain_isoform_DEGs_FDRq0.05.txt", 
                    header = TRUE, sep = "\t")
kallisto_kidney <- read.delim("../../results/kallisto/DEGs/LPS_Kidney_isoform_DEGs_FDRq0.05.txt", 
                     header = TRUE, sep = "\t")
kallisto_blood <- read.delim("../../results/kallisto/DEGs/LPS_Blood_isoform_DEGs_FDRq0.05.txt", 
                     header = TRUE, sep = "\t")
```

# Subset lists

```{r}
up_kallisto_brain <- subset(kallisto_brain$gene_name, kallisto_brain$b > 0)
down_kallisto_brain <- subset(kallisto_brain$gene_name, kallisto_brain$b < 0)

up_kallisto_kidney <- subset(kallisto_kidney$gene_name, kallisto_kidney$b > 0)
down_kallisto_kidney <- subset(kallisto_kidney$gene_name, kallisto_kidney$b < 0)

up_kallisto_blood <- subset(kallisto_blood$gene_name, kallisto_blood$b > 0)
down_kallisto_blood <- subset(kallisto_blood$gene_name, kallisto_blood$b < 0)
```

```{r}
saveToPDF <- function(...) {
    d = dev.copy(pdf,...)
    dev.off(d)
}
```

# Compare brain and kidney
```{r}
list_input <- list("Brain down-regulated" = down_kallisto_brain,
                   "Brain up-regulated" = up_kallisto_brain,
                   "Kidney down-regulated" = down_kallisto_kidney,
                   "Kidney up-regulated" = up_kallisto_kidney,
                   "Blood down-regulated" = down_kallisto_blood,
                   "Blood up-regulated" = up_kallisto_blood)
data <- fromList(list_input)
upset_gene <- upset(data, set_sizes=FALSE,
      c('Brain down-regulated','Brain up-regulated','Kidney down-regulated', 'Kidney up-regulated', 'Blood down-regulated', 'Blood up-regulated'),
  queries=list(
    upset_query(set='Brain down-regulated', fill='blue'),
    upset_query(set='Brain up-regulated', fill='red'),
    upset_query(set='Kidney down-regulated', fill='blue'),
    upset_query(set='Kidney up-regulated', fill='red'),
    upset_query(set='Blood down-regulated', fill='blue'),
    upset_query(set='Blood up-regulated', fill='red')
  ),
  base_annotations=list(
    'Intersection size'=(
        intersection_size(
        bar_number_threshold=1,  # show all numbers on top of bars
        width=0.5,   # reduce width of the bars
      )
      # add some space on the top of the bars
      + scale_y_continuous(expand=expansion(mult=c(0, 0.05)))
      + theme(
          # hide grid lines
          panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          # show axis lines
          axis.line=element_line(colour='black')
      )
    )
  ),
  stripes=upset_stripes(
    geom=geom_segment(size=12),  # make the stripes larger
    colors=c('grey95', 'white')
  ),
  # to prevent connectors from getting the colorured
  # use `fill` instead of `color`, together with `shape='circle filled'`
  matrix=intersection_matrix(
      geom=geom_point(
        shape='circle filled',
        size=3,
        stroke=0.45
      )
  ),
 # set_sizes=(
#    upset_set_size(geom=geom_bar(width=0.4))
 #   + theme(
#      axis.line.x=element_line(colour='black'),
#      axis.ticks.x=element_line()
#    )
#  ),
  sort_sets='descending',
  sort_intersections='descending'
)
upset_gene

# save
path <- "../../results/upset/LPS_brain_kidney_blood_kallisto_upset_plot"
saveToPDF(paste0(path, ".pdf"), width = 8.5, height = 5)
saveToPNG(paste0(path, ".png"), width = 6, height = 4, unit = "in", res = 300)

shared_up <- Reduce(intersect, list(up_kallisto_kidney, up_kallisto_brain, up_kallisto_blood))
write.table(shared_up, "../../results/upset/LPS_brain_kidney_blood_kallisto_shared_up.txt", sep = "\t", row.names = FALSE, quote = FALSE)
shared_down <- Reduce(intersect, list(down_kallisto_kidney, down_kallisto_brain, down_kallisto_blood))
write.table(shared_down, "../../results/upset/LPS_brain_kidney_blood_kallisto_shared_down.txt", sep = "\t", row.names = FALSE, quote = FALSE)
```
